# All Greetings:
GET http://localhost:8080/api/greeting HTTP/1.1

### Get Gretting id 1:
GET http://localhost:8080/api/greeting/1 HTTP/1.1

### Create Gretting:
POST http://localhost:8080/api/greeting HTTP/1.1
content-type: application/json

{    
    "content": "New Name"
}

### Update Gretting id 1:
PUT http://localhost:8080/api/greeting HTTP/1.1
content-type: application/json

{
    "id": "2",
    "content": "Updated Name"
}

### Delete Gretting:
DELETE http://localhost:8080/api/greeting/2 HTTP/1.1

### Error messsage:
GET http://localhost:8080/api/greeting-error HTTP/1.1

### Filter:
GET http://localhost:8080/api/greeting/filter/q?content=Upd HTTP/1.1




### All Books:
GET http://localhost:8080/api/book HTTP/1.1

### Get first Book:
GET http://localhost:8080/api/book/1 HTTP/1.1

### Create Book:
POST http://localhost:8080/api/book HTTP/1.1
content-type: application/json

{    
    "title": "New Title",
    "author": "New Author"
}